const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'../public'),origin='http://college.test';
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{for(const width of [390,1280]){
 const context=await browser.newContext({viewport:{width,height:900}}),errors=[],requests=[],posts=[];let active=false,cardLocked=false,picks={},tie=null;
 const game={eventId:'c1',gameIndex:0,away:'TEX',home:'OU',awayName:'Texas',homeName:'Oklahoma',awayRank:1,homeRank:4,kickoff:'2026-10-03T18:00:00Z',completed:false};
 await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());requests.push(u.pathname);const json=d=>route.fulfill({json:d});
  if(u.pathname==='/new-build/api/college'){
   if(req.method()==='POST'){const b=req.postDataJSON();posts.push(b);assert.equal(req.headers().authorization,'Bearer test');if(b.action==='access')active=b.active;if(b.action==='pick')picks[b.eventId]=b.team;if(b.action==='tie')tie=Number(b.guess);if(b.action==='lock')cardLocked=b.locked;return json({success:true})}
   const week=Number(u.searchParams.get('week')||5),view=u.searchParams.get('view');return json({pool:{id:1,name:'Office',code:'OFFICE'},week,currentWeek:5,role:'admin',player:'Alice',games:[game],deadline:Date.parse(game.kickoff),closed:false,active:week===5&&active,cardLocked:week===5&&cardLocked,picks:week===5?picks:{},tie:week===5?tie:null,candidates:[game],slateFrozen:false,members:[{name:'Alice',active}],players:[],rows:[],finalizedWinners:[],allFinal:false})
  }
  if(u.pathname.includes('/api/'))return json({});
  const file=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(u.origin===origin&&file.startsWith(root+path.sep)&&fs.existsSync(file)&&fs.statSync(file).isFile())return route.fulfill({body:fs.readFileSync(file),contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html'});return route.fulfill({body:''});
 });
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:new Date('2026-09-29T12:00:00Z')});await page.addInitScript(()=>{localStorage.setItem('links-current-pool',JSON.stringify({id:1}));localStorage.setItem('links-player-id','Alice');localStorage.setItem('links-player-name','Alice');localStorage.setItem('links-legacy-token','test')});
 await page.goto(origin+'/new-build/college.html?pool=1');await page.waitForSelector('#pendingPopup[open]');assert.equal(await page.locator('#week').inputValue(),'5');assert.equal(await page.locator('[data-team]:disabled').count(),2);await page.locator('#pendingPopup button').click();
 await page.locator('[data-view=admin]').click();await page.locator('[data-member]').waitFor({state:'attached'});await page.locator('[data-member]').evaluate(n=>{const d=n.closest('details');if(d)d.open=true});await page.locator('[data-member]').click();await page.waitForFunction(()=>document.querySelector('[data-member]')?.textContent.startsWith('ACTIVE'));
 await page.locator('[data-view=picks]').click();await page.waitForSelector('[data-team]:enabled');await page.locator('[data-team=TEX]').click();await page.waitForSelector('[data-team=TEX].chosen');await page.locator('#tie').fill('48');await page.locator('#lock').click();await page.waitForFunction(()=>document.querySelector('#lock')?.textContent==='UNLOCK MY PICKS');assert.equal(await page.locator('[data-team]:disabled').count(),2);
 await page.reload();await page.waitForFunction(()=>document.querySelector('#lock')?.textContent==='UNLOCK MY PICKS');await page.locator('#lock').click();await page.waitForSelector('[data-team]:enabled');
 await page.locator('[data-view=compare]').click();await page.waitForFunction(()=>document.querySelector('#content').textContent.includes('private until'));assert.equal(await page.locator('[data-view=compare]').getAttribute('href'), './college.html?pool=1&view=compare&week=5');
 await page.locator('[data-view=scores]').click();await page.waitForFunction(()=>document.querySelector('#content').textContent.includes('Texas at Oklahoma'));
 await page.locator('[data-view=picks]').click();await page.waitForSelector('#tie');await page.locator('#week').selectOption('6');await page.waitForSelector('#pendingPopup[open]');assert.equal(await page.locator('[data-team]:disabled').count(),2);await page.locator('#pendingPopup button').click();
 await page.locator('#currentWeek').click();await page.waitForFunction(()=>document.querySelector('#week').value==='5');await page.waitForSelector('[data-team]:enabled');
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'college-preview-'+width+'.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No horizontal overflow');assert.deepEqual(errors,[]);assert.ok(!requests.some(p=>/nfl|compare-picks|standings-v649/.test(p)),'College never requests NFL modules or endpoints');assert.ok(posts.every(p=>p.week===5));console.log('PASS college '+width+'px: independent navigation, current week, pending/access, picks, persistent locks, and privacy');await context.close();
 }}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
