import assert from 'node:assert/strict';import {fixture} from './helpers/pool-format-fixture.mjs';import {onRequest} from '../functions/new-build/api/last-alibi.js';import {buildCase,solve,view} from '../functions/lib/last-alibi.js';
const methods=new Set(),locations=new Set();for(let count=4;count<=8;count++)for(let trial=0;trial<100;trial++){const s={players:Object.fromEntries(Array.from({length:count},(_,i)=>['seat'+i,{id:'p'+i,name:'Player '+i}]))};buildCase(s);assert.equal(solve(s).length,1);assert.equal(solve(s)[0],s.players[s.case.killer].id);methods.add(s.case.method.id);locations.add(s.case.scene.id);const ids=s.case.evidence.map(e=>e.id);assert.equal(new Set(ids).size,ids.length);for(const [source,clock] of [['dinner','clock-0'],['gate','clock-1'],['recording','clock-2']]){const raw=s.case.evidence.find(e=>e.id===source).text.match(/device time 21:(\d+) to 21:(\d+)/),correction=s.case.evidence.find(e=>e.id===clock).text.match(/displayed 21:(\d+)/);assert.equal(Number(raw[1])-Number(correction[1]),Number(s.case.time.slice(2,4)));assert.equal(Number(raw[2])-Number(raw[1]),6)}s.phase='investigate';s.chapter=1;s.players.seat0.notes='private';s.owner='seat0';const tv=view(s,'',0,true);assert.equal(tv.privateRole,null);assert.equal(tv.notes,'');assert.equal(JSON.stringify(tv).includes('eliminates'),false);assert.equal(tv.ending,undefined)}assert.equal(methods.size,3);assert.equal(locations.size,3);
const {db}=fixture();async function call(body={},token='',query='',display=''){const r=await onRequest({env:{DB:db},request:new Request('https://alibi.local/new-build/api/last-alibi'+query,{method:body.action?'POST':'GET',headers:{Origin:'https://alibi.local','x-alibi-token':token,'x-alibi-display':display},...(body.action?{body:JSON.stringify({game:1,...body})}:{})})});return {status:r.status,...await r.json()}}
const h=await call({action:'create',mode:'secret',name:'Jake',minutes:45}),code=h.code,players=[h];assert.equal(h.status,200);for(const name of ['Amanda','Bob','Dana'])players.push(await call({action:'join',code,name}));const get=(p=players[0])=>call({},p.token,'?code='+code);assert.equal((await call({},'', '?code='+code)).status,401);for(const p of players)await call({action:'ready',code},p.token);let s=await call({action:'start',code},h.token);assert.equal(s.phase,'briefing');assert.equal((await call({action:'continue',code},players[1].token)).status,403);assert.equal((await call({action:'continue',code},h.token)).status,409);
function stored(){return JSON.parse(db.raw.prepare('SELECT state FROM links_mystery_rooms WHERE code=?').get(code).state)}function mutate(fn){const s=stored();fn(s);db.raw.prepare('UPDATE links_mystery_rooms SET state=? WHERE code=?').run(JSON.stringify(s),code)}
mutate(s=>s.guided=false);
await call({action:'notes',code,text:'Private deduction'},h.token);assert.equal((await get(players[1])).notes,'');const tv=await call({},'', '?code='+code,h.displayKey);assert.equal(tv.privateRole,null);assert.equal(tv.notes,'');assert.equal(tv.displayKey,undefined);assert.equal((await call({action:'pause',code},'', '',h.displayKey)).status,403);
await call({action:'pause',code},h.token);mutate(s=>s.deadline=Date.now()-1000);assert.equal((await get()).phase,'briefing');await call({action:'pause',code},h.token);mutate(s=>s.deadline=Date.now()-1);s=await get();assert.equal(s.chapter,1);assert.equal(s.phase,'investigate');assert.equal((await call({action:'inspect',code,chapter:1,id:'envelope'},h.token)).status,404);assert.equal((await call({action:'share',code,id:'dinner'},players[1].token)).status,403);
s=await call({action:'inspect',code,chapter:1,id:'dinner'},h.token);assert.ok(s.discovered.some(e=>e.id==='dinner'));assert.equal((await get(players[1])).discovered.length,0);await call({action:'share',code,id:'dinner'},h.token);assert.ok((await get(players[1])).publicClues.some(e=>e.id==='dinner'));
for(let i=0;i<4;i++){mutate(s=>s.deadline=Date.now()-1);s=await get()}assert.equal(s.phase,'accuse');assert.equal(s.publicClues.length,12);const raw=stored(),killer=raw.players[raw.case.killer].id;
for(const p of players){const mine=(await get(p)).players.find(x=>x.you).id;const target=mine===killer?Object.values(raw.players).find(x=>x.id!==killer).id:killer;assert.equal((await call({action:'accuse',code,suspect:target,scene:raw.case.scene.id,object:raw.case.object},p.token)).status,200)}assert.equal((await call({action:'accuse',code,suspect:killer,scene:'study',object:'staged fall'},h.token)).status,409);mutate(s=>s.deadline=Date.now()-1);s=await get();assert.equal(s.phase,'ended');assert.equal(s.ending.caught,true);assert.equal(s.players.filter(p=>p.score===700).length,3);assert.equal(s.players.find(p=>p.killer).score,0);
const previous=killer,method=raw.case.method.id;s=await call({action:'again',code},h.token);assert.equal(s.game,2);for(const p of players)await call({action:'ready',code,game:2},p.token);await call({action:'start',code,game:2},h.token);const fresh=stored();assert.notEqual(fresh.players[fresh.case.killer].id,previous);assert.notEqual(fresh.case.method.id,method);assert.equal((await call({action:'join',code,name:'Late'})).status,409);db.raw.prepare('UPDATE links_mystery_rooms SET expires=0 WHERE code=?').run(code);assert.equal((await get()).status,404);db.raw.close();console.log('PASS 500 generated cases: unique culprit and consistent timestamps across 4–8 players, three methods/locations; private roles/notes, TV read-only, timed chapters, pause, inspection/share permissions, final scoring, no consecutive culprit/method, expiry.');
