const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{for(const width of [1440,390]){
 const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];let opened=null;page.on('pageerror',e=>errors.push(e.message));
 const state={currentPool:'1',commissioner:true,verified:true,pools:[{id:'1',code:'BARNES',name:'Barnes Family and Friends Pick’em League',role:'admin',playerName:'Jake Doutt',games:['nfl','college','squares']},{id:'2',code:'OFFICE',name:'Office Pool',role:'player',playerName:'Jake',games:['nfl']}]};
 await page.addInitScript(()=>{if(location.pathname.endsWith('/nfl.html'))return;localStorage.setItem('links-token','test');localStorage.setItem('links-legacy-token','test');localStorage.setItem('links-account-token','account');localStorage.setItem('links-player-id','Jake Doutt');localStorage.setItem('links-player-name','Jake Doutt');localStorage.setItem('links-current-pool',JSON.stringify({id:'1',code:'BARNES',name:'Barnes Family'}));localStorage.setItem('links-partner-location','yes');window.testLatitude=40;Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(ok){ok({coords:{latitude:window.testLatitude,longitude:-90,accuracy:5}})}}});Object.defineProperty(navigator,'permissions',{value:{query:async()=>({state:'granted'})}})});
 await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.pathname.endsWith('/api/pool-switcher')){if(r.request().method()==='POST'){opened=r.request().postDataJSON();return r.fulfill({json:{token:'next',playerId:'Jake',gameKeys:['nfl'],pool:{id:'2',code:'OFFICE',name:'Office Pool',role:'player',games:['NFL Pick’em']}}})}return r.fulfill({json:state})}if(u.pathname.endsWith('/api/members'))return r.fulfill({json:{members:[{playerId:'Jake Doutt',displayName:'Jake Doutt'},{playerId:'a',displayName:'Jessica'},{playerId:'b',displayName:'Michael'},{playerId:'c',displayName:'Chris'},{playerId:'d',displayName:'Sam'}]}});if(u.pathname.endsWith('/api/login-name'))return r.fulfill({json:{displayName:'Jake Doutt',loginName:'Jake',names:[]}});if(u.pathname.endsWith('/api/partners'))return r.fulfill({json:{partners:[{id:'p',name:'Family Café',logo:'/links-small-logo.png',offer:'Game day specials for the whole family.',website:'https://example.com',latitude:40,longitude:-90,radius:50,address:'1 Main'}]}});if(u.pathname.includes('/api/'))return r.fulfill({json:{}});if(u.pathname.endsWith('/nfl.html'))return r.fulfill({contentType:'text/html',body:'<p>Game opened</p>'});const file=path.join('public',decodeURIComponent(u.pathname));if(fs.existsSync(file)&&fs.statSync(file).isFile())return r.fulfill({contentType:file.endsWith('.js')||file.endsWith('.mjs')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html',body:fs.readFileSync(file)});return r.fulfill({status:404,body:''})});
 await page.goto('https://fixture/new-build/control-center.html?pool=BARNES');await page.getByRole('heading',{name:'Jake Doutt’s Locker Room'}).waitFor();assert.equal(await page.locator('#linksPartnerBanner').count(),0);assert.equal(await page.locator('.wall-panel img[src="/links-small-logo.png"]').count(),2);assert.equal(await page.locator('.game-plaque').count(),4);await page.locator('.jersey-name.me').waitFor();assert.equal(await page.locator('.jersey-name.me').textContent(),'Jake Doutt');assert.equal(await page.locator('.pool-name.long-name').count(),3);assert.equal(await page.getByRole('button',{name:'Barnes Family and Friends Pick’em League · Squares'}).isDisabled(),false);assert.equal(await page.getByRole('button',{name:'Connect My Pools',exact:true}).isEnabled(),true);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.getByRole('button',{name:'Next pool games'}).click();await page.waitForTimeout(400);assert.ok(await page.locator('#topGameGrid').evaluate(e=>e.scrollLeft)>0);
 assert.equal(await page.locator('#partnerIdentity').isVisible(),width>900);assert.equal(await page.locator('#partnerOffer').isVisible(),width>900);await page.locator('#topGameGrid').evaluate(e=>e.scrollLeft=0);await page.waitForTimeout(100);fs.mkdirSync('output/locker-room',{recursive:true});await page.screenshot({path:'output/locker-room/'+width+'.png',fullPage:true});
 await page.getByRole('button',{name:'My Profile',exact:true}).click();await page.getByRole('button',{name:'Close My Profile'}).click();await page.waitForTimeout(100);
 await page.getByRole('button',{name:'Office Pool · NFL Pick’em',exact:true}).click();await page.waitForURL('**/nfl.html?**');assert.deepEqual(opened,{action:'open',pool:'2'});assert.equal(await page.evaluate(()=>localStorage.getItem('links-token')),'next');assert.ok(page.url().includes('pool=2'));assert.equal(errors.length,0,errors.join('\n'));console.log('PASS Locker Room '+width+'px: names, memberships, partner panels, scrolling, profile, secure pool switch');await page.close();
 }}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
