const {chromium}=require('playwright'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{for(const width of [390,1280]){const page=await browser.newPage({viewport:{width,height:850}}),errors=[];page.on('pageerror',e=>errors.push(e.message));let list=[{id:'a',name:'Bar A',logo:'https://example.com/a.png',website:'https://example.com',address:'1 Main',offer:'Offer A',latitude:40,longitude:-90,radius:50},{id:'b',name:'Bar B',logo:'https://example.com/b.png',website:'https://example.com',address:'2 Main',offer:'Offer B',latitude:41,longitude:-90,radius:50}];
await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.pathname.endsWith('/api/partners'))return r.fulfill({json:{partners:list}});if(u.pathname.endsWith('.mjs'))return r.fulfill({contentType:'text/javascript',body:fs.readFileSync('public/new-build/'+u.pathname.split('/').pop(),'utf8')});if(u.hostname==='example.com')return r.fulfill({status:404});return r.fulfill({contentType:'text/html',body:'<meta name="viewport" content="width=device-width"><main><section id="pools">My Pools</section></main><script type="module">import {mountPartners} from "./partner-banner.mjs";mountPartners(document.getElementById("pools"))</script>'})});
await page.addInitScript(()=>{window.geoCalls=0;window.lat=40;window.fail=false;Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(ok,bad){window.geoCalls++;if(window.delay){window.pending=ok;return}if(window.fail)bad({code:1});else ok({coords:{latitude:window.lat,longitude:-90,accuracy:10}})}}});Object.defineProperty(navigator,'permissions',{value:{query:async()=>({state:'granted'})}})});
await page.goto('https://fixture/new-build/nfl.html');await page.getByRole('button',{name:'Show partners near me'}).waitFor();assert.equal(await page.evaluate(()=>geoCalls),0);await page.getByRole('button',{name:'Show partners near me'}).click();await page.getByRole('heading',{name:'Bar A',exact:true}).waitFor();
await page.evaluate(()=>{window.lat=41;window.delay=true;document.dispatchEvent(new Event('visibilitychange'))});await page.getByText('Checking nearby partners…').waitFor();assert.equal(await page.getByRole('heading',{name:'Bar A',exact:true}).count(),0);await page.evaluate(()=>{window.delay=false;window.pending({coords:{latitude:41,longitude:-90,accuracy:10}})});await page.getByRole('heading',{name:'Bar B',exact:true}).waitFor();
await page.evaluate(()=>window.fail=true);await page.getByRole('button',{name:'Check my location again'}).click();await page.getByText('Location or partner information is unavailable. No bar has been selected.').waitFor();assert.equal(await page.getByRole('heading',{name:'Bar B',exact:true}).count(),0);
list.push({...list[1],id:'c',name:'Next door',website:''});await page.evaluate(()=>window.fail=false);await page.getByRole('button',{name:'Show partners near me'}).click();await page.getByText('Location cannot confirm which bar you are visiting. Choose your bar:').waitFor();await page.getByRole('button',{name:'Next door — 2 Main'}).click();await page.getByRole('heading',{name:'Next door',exact:true}).waitFor();assert.equal(await page.getByRole('link',{name:'View Offer'}).count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.getByRole('button',{name:'Turn off location ads'}).click();assert.equal(await page.evaluate(()=>localStorage.getItem('links-partner-location')),null);await page.evaluate(()=>window.delay=true);await page.getByRole('button',{name:'Show partners near me'}).click();await page.getByText('Checking nearby partners…').waitFor();await page.getByRole('button',{name:'Dismiss partner banner'}).click();await page.evaluate(()=>window.pending({coords:{latitude:40,longitude:-90,accuracy:10}}));assert.equal(await page.locator('#linksPartnerBanner').isVisible(),false);assert.equal(errors.length,0,errors.join(';'));await page.close();console.log('PASS partner banner '+width+'px: opt-in, venue change, old-ad clearing, denied location, ambiguity, opt-out and width');}}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});

