import {partyFinish,savePartyRoom} from '../../lib/party-scoreboard.js';
import {requirePartyPass} from '../../lib/party-access.js';
import {begin,next,advance,view} from '../../lib/last-alibi.js';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}}),hash=async t=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t)))).map(n=>n.toString(16).padStart(2,'0')).join('');
export async function onRequest({request,env}){try{
 const db=env.DB,u=new URL(request.url),now=Date.now();if(!db)return json({error:'Mystery unavailable.'},503);if(!['GET','POST'].includes(request.method))return json({error:'Method not allowed.'},405);if(request.method==='POST'&&request.headers.get('Origin')!==u.origin)return json({error:'Open Last Alibi on LINKS first.'},403);
 let b={};if(request.method==='POST'){const raw=await request.text();if(raw.length>8000)return json({error:'Request too large.'},413);try{b=JSON.parse(raw)}catch{return json({error:'Invalid request.'},400)}}
 const action=b.action||'state';await db.batch([db.prepare('CREATE TABLE IF NOT EXISTS links_mystery_rooms(code TEXT PRIMARY KEY,state TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 0,expires INTEGER NOT NULL)'),db.prepare('CREATE TABLE IF NOT EXISTS links_mystery_limits(id TEXT PRIMARY KEY,starts INTEGER NOT NULL,hits INTEGER NOT NULL)')]);
 if(request.method==='POST'){await db.prepare('DELETE FROM links_mystery_rooms WHERE expires<=?').bind(now).run();const id=await hash((request.headers.get('CF-Connecting-IP')||'local')+':'+(action==='create'?'create':'action')),window=action==='create'?3600000:60000,limit=action==='create'?10:180;await db.prepare('INSERT INTO links_mystery_limits(id,starts,hits) VALUES(?,?,1) ON CONFLICT(id) DO UPDATE SET hits=CASE WHEN starts<? THEN 1 ELSE hits+1 END,starts=CASE WHEN starts<? THEN excluded.starts ELSE starts END').bind(id,now,now-window,now-window).run();if((await db.prepare('SELECT hits FROM links_mystery_limits WHERE id=?').bind(id).first()).hits>limit)return json({error:'Please wait before trying again.'},429)}
 const name=String(b.name||'').trim(),validName=name.length>0&&name.length<=32;
 if(action==='create'){const paymentGate=await requirePartyPass(request,env);if(paymentGate)return paymentGate;if(!validName||![35,45].includes(b.minutes))return json({error:'Enter your name and choose the game length.'},400);const code=crypto.randomUUID().replace(/-/g,'').slice(0,10).toUpperCase(),token=crypto.randomUUID()+crypto.randomUUID(),seat=await hash(token),s={code,owner:seat,displayKey:crypto.randomUUID()+crypto.randomUUID(),game:1,mode:['solo','secret'].includes(b.mode)?b.mode:'together',guided:true,minutes:b.minutes,phase:'lobby',players:{[seat]:{id:crypto.randomUUID(),name,ready:false}}};await db.prepare('INSERT INTO links_mystery_rooms(code,state,expires) VALUES(?,?,?)').bind(code,JSON.stringify(s),now+14400000).run();return json({...view(s,seat,now),token})}
 const code=String(b.code||u.searchParams.get('code')||'').toUpperCase();if(!/^[A-F0-9]{10}$/.test(code))return json({error:'Enter a valid room code.'},400);const token=request.headers.get('x-alibi-token')||'',seat=token?await hash(token):'',displayKey=request.headers.get('x-alibi-display')||'';
 for(let attempt=0;attempt<5;attempt++){const row=await db.prepare('SELECT * FROM links_mystery_rooms WHERE code=? AND expires>?').bind(code,Date.now()).first();if(!row)return json({error:'Room expired or not found. Start a new mystery.'},404);const s=JSON.parse(row.state),time=Date.now(),display=!!displayKey&&displayKey===s.displayKey;let changed=advance(s,time),issued,current=seat;const completed=partyFinish(s);
 if(action==='join'){if(!s.players[seat]){if(s.mode==='solo'||s.phase!=='lobby'||Object.keys(s.players).length>=8)return json({error:'This case has started or the room is full.'},409);if(!validName||Object.values(s.players).some(p=>p.name.toLowerCase()===name.toLowerCase()))return json({error:'Enter an unused name (up to 32 characters).'},400);issued=crypto.randomUUID()+crypto.randomUUID();current=await hash(issued);s.players[current]={id:crypto.randomUUID(),name,ready:false};changed=true}}
 else{if(!s.players[seat]&&!display)return json({error:'Join this room first.'},401);if(display&&action!=='state')return json({error:'TV screens cannot control the case.'},403);const p=s.players[seat];if(action!=='state'&&b.game!==s.game)return json({error:'This game has moved on. Refresh your screen.'},409);
 if(action==='ready'){if(s.phase!=='lobby')return json({error:'The case has started.'},409);p.ready=!p.ready;changed=true}
 else if(action==='chapter-ready'){if(!s.guided||s.pausedAt||!['briefing','investigate'].includes(s.phase)||b.chapter!==s.chapter)return json({error:'This chapter has moved on.'},409);p.chapterReady=!p.chapterReady;changed=true}
 else if(action==='start'){if(seat!==s.owner)return json({error:'Only the creator can start.'},403);if(s.phase!=='lobby'||Object.keys(s.players).length<(s.mode==='solo'?1:s.mode==='secret'?4:2)||!Object.values(s.players).every(p=>p.ready))return json({error:'Everyone must be ready. Solve Together needs 2–8 players; Secret Killer needs 4–8.'},409);begin(s,time);changed=true}
 else if(action==='inspect'){if(s.phase!=='investigate'||b.chapter!==s.chapter)return json({error:'Wait for the investigation chapter.'},409);const e=s.case.evidence.find(e=>e.id===b.id&&e.chapter<=s.chapter);if(!e)return json({error:'This object is not available yet.'},404);const known=Object.values(p.searched).flat();if(!known.includes(e.id)&&!s.published.includes(e.id)){p.searched[s.chapter]||=[];if(s.mode!=='solo'&&p.searched[s.chapter].length>=3)return json({error:'You have collected three clues this chapter. Compare evidence or ask another guest to inspect.'},409);p.searched[s.chapter].push(e.id);changed=true}}
 else if(action==='share'){if(!s.case||!Object.values(p.searched||{}).flat().includes(b.id))return json({error:'Inspect the clue first.'},403);if(!s.published.includes(b.id)){s.published.push(b.id);changed=true}}
 else if(action==='notes'){const text=String(b.text||'');if(text.length>4000)return json({error:'Keep notes under 4,000 characters.'},400);p.notes=text;changed=true}
 else if(action==='accuse'){if(s.phase!=='accuse'||s.pausedAt||p.accusation)return json({error:'Accusation locked or the game is paused.'},409);if(!Object.values(s.suspects||s.players).some(x=>x.id===b.suspect)||b.suspect===p.id||!s.case||!['study','conservatory','gallery'].includes(b.scene)||!['bronze presentation clock','tampered drink','staged fall'].includes(b.object))return json({error:'Choose a suspect, location, and method.'},400);if(s.guided&&!s.case.evidence.some(e=>e.id===b.evidence&&s.published.includes(e.id)))return json({error:'Choose a shared record to support your conclusion.'},400);p.accusation={suspect:b.suspect,scene:b.scene,object:b.object,evidence:b.evidence||null};changed=true}
 else if(['pause','continue','again'].includes(action)){if(seat!==s.owner)return json({error:'Only the room creator can control the pace.'},403);
 if(action==='pause'){if(!['briefing','investigate','accuse'].includes(s.phase))return json({error:'No active chapter to pause.'},409);if(s.pausedAt){s.deadline+=time-s.pausedAt;s.pausedAt=null}else s.pausedAt=time;changed=true}
 if(action==='continue'){if(s.pausedAt||!['briefing','investigate','accuse'].includes(s.phase)||time-s.phaseStarted<45000)return json({error:'Allow at least 45 seconds to read this chapter. Resume first if paused.'},409);if(s.guided&&!(s.phase==='accuse'?Object.values(s.players).every(p=>p.accusation):Object.values(s.players).every(p=>p.chapterReady)))return json({error:'Wait for everyone to finish and tap ready.'},409);next(s,time);changed=true}
 if(action==='again'){if(s.phase!=='ended')return json({error:'Finish this mystery first.'},409);s.phase='lobby';s.game++;s.chapter=0;delete s.case;delete s.suspects;s.cooperative=false;s.published=[];for(const p of Object.values(s.players)){p.ready=false;p.notes='';delete p.character;delete p.accusation}changed=true}
 }else if(action!=='state')return json({error:'Unknown action.'},400)}
 if(changed){const r=await savePartyRoom(db,'last-alibi',code,row.version,s,completed);if(!r.meta?.changes)continue}return json({...view(s,current,time,display),...(issued?{token:issued}:{})})
 }return json({error:'Room busy. Try again.'},409);
 }catch{return json({error:'Unable to complete that request. Please try again.'},503)}}
