const json=(d,s=200)=>Response.json(d,{status:s,headers:{"Cache-Control":"no-store"}});
async function resolvePool(db,value){const raw=String(value||"").trim();if(/^\d+$/.test(raw)){const p=await db.prepare("SELECT id,code,name FROM pools WHERE id=? LIMIT 1").bind(Number(raw)).first();if(p)return p}return raw?await db.prepare("SELECT id,code,name FROM pools WHERE upper(code)=upper(?) OR lower(trim(name))=lower(trim(?)) LIMIT 1").bind(raw,raw).first():null}
export async function onRequestGet({request,env}){
 const db=env.DB;if(!db)return json({success:false,error:"Legacy LINKS database binding DB is unavailable",build:"634"},503);
 const q=new URL(request.url).searchParams,p=await resolvePool(db,q.get("pool")),week=Number(q.get("week")||0),player=String(q.get("player")||"").trim();
 if(!p)return json({success:false,error:"Pool not found"},404);
 if(week&&player){const r=await db.prepare("SELECT game_index AS gameIndex,team FROM pool_picks WHERE pool_id=? AND sport='nfl' AND player_name=? AND week=? ORDER BY game_index").bind(p.id,player,week).all(),t=await db.prepare("SELECT guess AS tieGuess FROM pool_ties WHERE pool_id=? AND sport='nfl' AND player_name=? AND week=? LIMIT 1").bind(p.id,player,week).first();return json({success:true,week,player,rows:r.results||[],tieGuess:t?.tieGuess??null,resolvedPoolId:String(p.id),dataSource:"legacy-production-DB",build:"634"})}
 const picks=await db.prepare("SELECT week,COUNT(*) count FROM pool_picks WHERE pool_id=? AND sport='nfl' GROUP BY week ORDER BY week").bind(p.id).all(),ties=await db.prepare("SELECT week,COUNT(*) count FROM pool_ties WHERE pool_id=? AND sport='nfl' GROUP BY week ORDER BY week").bind(p.id).all();return json({success:true,picks:picks.results||[],tiebreakers:ties.results||[],resolvedPoolId:String(p.id),dataSource:"legacy-production-DB",build:"634"});
}
export async function onRequestPost(){return json({success:false,error:"Historical import is disabled because New Build now reads the existing LINKS database directly.",build:"634"},410)}