import {withTriviaSession} from '../../lib/trivia-sessions.js';
import {partyFinish,savePartyRoom} from '../../lib/party-scoreboard.js';
import {requirePartyPass} from '../../lib/party-access.js';
import {loadBank,prepareTurn,prepareDuel,advance,act,view} from '../../lib/million-point.js';
const json=(v,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store'}});
const hash=async t=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t)))).map(n=>n.toString(16).padStart(2,'0')).join('');
async function handleRequest({request,env}){try{
 const u=new URL(request.url),db=env.DB,now=Date.now();if(!db)return json({error:'Game temporarily unavailable.'},503);if(!['GET','POST'].includes(request.method))return json({error:'Method not allowed.'},405);if(request.method==='POST'&&request.headers.get('Origin')!==u.origin)return json({error:'Open this game on LINKS first.'},403);
 let b={};if(request.method==='POST'){if(Number(request.headers.get('Content-Length'))>4000)return json({error:'Request too large.'},413);const text=await request.text();if(text.length>4000)return json({error:'Request too large.'},413);try{b=JSON.parse(text)}catch{return json({error:'Invalid request.'},400)}}const action=b.action||'state';const remembered=(request.headers.get('Cookie')||'').match(/(?:^|;\s*)links_million_history=([a-f0-9]{32})(?:;|$)/)?.[1];
 await db.batch([db.prepare('CREATE TABLE IF NOT EXISTS links_million_rooms(code TEXT PRIMARY KEY,state TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 0,expires INTEGER NOT NULL)'),db.prepare('CREATE TABLE IF NOT EXISTS links_million_limits(id TEXT PRIMARY KEY,starts INTEGER NOT NULL,hits INTEGER NOT NULL)')]);
 await db.prepare('CREATE TABLE IF NOT EXISTS links_million_history(id TEXT PRIMARY KEY,history TEXT NOT NULL,expires INTEGER NOT NULL)').run();
 await db.prepare('DELETE FROM links_million_history WHERE expires<=?').bind(now).run();
 await db.batch([db.prepare('DELETE FROM links_million_rooms WHERE expires<=?').bind(now),db.prepare('DELETE FROM links_million_limits WHERE starts<?').bind(now-86400000)]);
 if(request.method==='POST'){const duration=action==='create'?3600000:60000,limit=action==='create'?6:120,id=await hash((request.headers.get('CF-Connecting-IP')||'local')+':'+(action==='create'?'create':'play'));await db.prepare('INSERT INTO links_million_limits VALUES(?,?,1) ON CONFLICT(id) DO UPDATE SET hits=CASE WHEN starts<? THEN 1 ELSE hits+1 END,starts=CASE WHEN starts<? THEN excluded.starts ELSE starts END').bind(id,now,now-duration,now-duration).run();if((await db.prepare('SELECT hits FROM links_million_limits WHERE id=?').bind(id).first()).hits>limit)return json({error:'Please wait before trying again.'},429)}
 const name=String(b.name||'').trim();if(['create','join'].includes(action)&&(!name||name.length>32))return json({error:'Enter a name up to 32 characters.'},400);
 if(action==='create'){const paymentGate=await requirePartyPass(request,env);if(paymentGate)return paymentGate;if(!['hotseat','duel'].includes(b.mode))return json({error:'Choose a game mode.'},400);const code=crypto.randomUUID().replace(/-/g,'').slice(0,10).toUpperCase(),token=crypto.randomUUID()+crypto.randomUUID(),seat=await hash(token),s={code,historyId:remembered||crypto.randomUUID().replace(/-/g,''),mode:b.mode,game:1,phase:'lobby',phaseId:0,owner:seat,displayKey:crypto.randomUUID()+crypto.randomUUID(),players:{[seat]:{name,ready:false,score:0}}};await db.prepare('INSERT INTO links_million_rooms(code,state,expires) VALUES(?,?,?)').bind(code,JSON.stringify(s),now+86400000).run();const response=json({...view(s,seat,now),token});response.headers.set('Set-Cookie','links_million_history='+s.historyId+'; Path=/new-build/api/million-point; Max-Age=2592000; HttpOnly; SameSite=Lax'+(u.protocol==='https:'?'; Secure':''));return response}
 const code=String(b.code||u.searchParams.get('code')||'').toUpperCase();if(!/^[A-F0-9]{10}$/.test(code))return json({error:'Enter your room code.'},400);const token=request.headers.get('x-million-token')||'',seat=token?await hash(token):'',displayKey=request.headers.get('x-million-display')||'';let bank;
 for(let retry=0;retry<5;retry++){const row=await db.prepare('SELECT * FROM links_million_rooms WHERE code=? AND expires>?').bind(code,Date.now()).first();if(!row)return json({error:'Room expired or not found.'},404);const s=JSON.parse(row.state),display=!!displayKey&&displayKey===s.displayKey;let current=seat,issued;
 if(action!=='join'&&!s.players[seat]&&!display)return json({error:'Join this room first.'},401);if(display&&action!=='state')return json({error:'TV display is read only.'},403);let changed=advance(s,Date.now());const completed=partyFinish(s);
 if(action==='join'){if(s.phase!=='lobby'&&!s.players[seat])return json({error:'The game has started. Join the next game.'},409);if(!s.players[seat]){if(Object.keys(s.players).length>=(s.mode==='duel'?2:8))return json({error:'This room is full.'},409);if(Object.values(s.players).some(p=>p.name.toLowerCase()===name.toLowerCase()))return json({error:'That name is already taken.'},409);issued=crypto.randomUUID()+crypto.randomUUID();current=await hash(issued);s.players[current]={name,ready:false,score:0};changed=true}}
 else if(action==='ready'){if(s.phase!=='lobby')return json({error:'The game has started.'},409);s.players[seat].ready=!s.players[seat].ready;changed=true}
 else if(action==='start'){if(seat!==s.owner)return json({error:'Only the room creator can start.'},403);if(s.phase!=='lobby'||(s.mode==='duel'&&Object.keys(s.players).length!==2)||!Object.values(s.players).every(p=>p.ready))return json({error:'Everyone must tap Ready first.'},409);s.historyId ||= remembered;const history=s.historyId?await db.prepare('SELECT history FROM links_million_history WHERE id=? AND expires>?').bind(s.historyId,Date.now()).first():null;const recent=history?JSON.parse(history.history):{};s.seen=[...new Set([...(recent.ids||[]),...(s.seen||[])])].slice(-1500);s.seenTexts=[...new Set([...(recent.texts||[]),...(s.seenTexts||[])])].slice(-1500);bank ||= loadBank(env,s.seen,s.seenTexts);const loaded=await bank;s.bank=loaded.questions;s.notice=loaded.notice;s.order=Object.keys(s.players);s.turn=0;(s.mode==='duel'?prepareDuel:prepareTurn)(s,Date.now());changed=true}
 else if(action==='next'){if(seat!==s.owner||s.phase!=='turnEnd'||b.game!==s.game||b.phaseId!==s.phaseId)return json({error:'Wait for the creator to move to the next seat.'},409);s.turn++;if(s.turn>=s.order.length){s.phase='ended';s.phaseId++}else prepareTurn(s,Date.now());changed=true}
 else if(action==='again'){if(seat!==s.owner||s.phase!=='ended'||b.game!==s.game)return json({error:'Finish this game first.'},409);s.phase='lobby';s.phaseId++;s.game++;s.deadline=0;s.order=[];delete s.deck;delete s.bank;delete s.duel;s.turn=0;s.level=0;s.earned=0;s.safe=0;for(const p of Object.values(s.players)){p.ready=false;p.score=0}changed=true}
 else if(action!=='state'){try{act(s,seat,b,Date.now())}catch(e){return json({error:e.message},409)}changed=true}
 if(changed){const r=await savePartyRoom(db,'million-point',code,row.version,s,completed);if(!r.meta?.changes)continue;if(s.historyId&&s.seen?.length){const row=await db.prepare('SELECT history FROM links_million_history WHERE id=?').bind(s.historyId).first();const old=row?JSON.parse(row.history):{};const ids=[...(old.ids||[]).filter(id=>!s.seen.includes(id)),...s.seen].slice(-1500),texts=[...(old.texts||[]).filter(t=>!s.seenTexts?.includes(t)),...(s.seenTexts||[])].slice(-1500);await db.prepare('INSERT INTO links_million_history(id,history,expires) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET history=excluded.history,expires=excluded.expires').bind(s.historyId,JSON.stringify({ids,texts}),Date.now()+2592000000).run()}}return json({...view(s,current,Date.now(),display),...(issued?{token:issued}:{})});
 }return json({error:'Room busy. Please try again.'},409);
 }catch{return json({error:'Unable to complete the request. Your room is saved; please retry.'},503)}}

export const onRequest=context=>withTriviaSession(context,"million-point",handleRequest);
