const json=(d,s=200)=>Response.json(d,{status:s,headers:{"Cache-Control":"no-store"}});
export async function onRequestGet({request,env}){
 const db=env.LINKS_DB||env.DB;if(!db)return json({success:false,code:"DB_NOT_AVAILABLE",error:"LINKS database is not available"},503);
 const q=new URL(request.url).searchParams,pool=q.get("pool"),game=q.get("game"),period=q.get("period"),player=q.get("player");
 if(!pool||!game||!period||!player)return json({success:false,error:"pool, game, period and player are required"},400);
 try{const {results=[]}=await db.prepare("SELECT event_id AS eventId,selection,points,locked_at AS lockedAt,saved_at AS savedAt FROM picks WHERE pool_id=? AND player_id=? AND game_type=? AND period_key=?").bind(pool,player,game,period).all();return json({success:true,picks:results})}catch{return json({success:false,error:"Pick lookup unavailable"},500)}
}
const feeds={"NFL Pick’em":"https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard","College Pick’em":"https://site.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard","Confidence":"https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard","Game 33":"https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard","Survivor":"https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard","March Madness":"https://site.api.espn.com/apis/site/v2/sports/basketball/mens-college-basketball/scoreboard"};
async function trustedStart(game,eventId){const url=feeds[game];if(!url)return null;const r=await fetch(url,{headers:{"Accept":"application/json"}});if(!r.ok)throw new Error("schedule");const j=await r.json(),e=(j.events||[]).find(x=>String(x.id)===String(eventId));return e?.date?Date.parse(e.date):NaN}
export async function onRequestPost({request,env}){
 const db=env.LINKS_DB||env.DB;if(!db)return json({success:false,code:"DB_NOT_AVAILABLE",error:"LINKS database is not available"},503);
 let b;try{b=await request.json()}catch{return json({success:false,error:"Invalid request"},400)}
 const pool=String(b.pool||""),player=String(b.player||""),game=String(b.game||""),period=String(b.period||""),eventId=String(b.eventId||""),selection=String(b.selection||"");
 if(!pool||!player||!game||!period||!eventId||!selection)return json({success:false,error:"Incomplete pick"},400);
 if(eventId==="__TIEBREAKER__"){const n=Number(selection);if(!Number.isInteger(n)||n<0||n>200)return json({success:false,error:"Tiebreaker must be a whole-number combined score from 0 to 200"},400);try{const membership=await db.prepare("SELECT status FROM memberships WHERE pool_id=? AND player_id=? LIMIT 1").bind(pool,player).first();if(!membership||membership.status!=="active")return json({success:false,error:"Active pool membership required"},403);const id=crypto.randomUUID(),savedAt=new Date().toISOString();await db.prepare("INSERT INTO picks(id,pool_id,player_id,game_type,period_key,event_id,selection,points,saved_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(pool_id,player_id,game_type,period_key,event_id) DO UPDATE SET selection=excluded.selection,saved_at=excluded.saved_at").bind(id,pool,player,game,period,eventId,String(n),null,savedAt).run();return json({success:true,eventId,selection:String(n),savedAt})}catch{return json({success:false,error:"Tiebreaker save unavailable"},500)}}
 let start;if(feeds[game]){try{start=await trustedStart(game,eventId)}catch{return json({success:false,error:"Official schedule could not be verified"},503)}if(!Number.isFinite(start))return json({success:false,error:"Game was not found on the official schedule"},404)}else{try{const cfg=await db.prepare("SELECT lock_at AS lockAt FROM pool_game_settings WHERE pool_id=? AND game_type=? AND period_key=? LIMIT 1").bind(pool,game,period).first();start=Date.parse(cfg?.lockAt||"")}catch{return json({success:false,error:"Configured deadline could not be verified"},503)}if(!Number.isFinite(start))return json({success:false,error:"Commissioner must set a lock deadline before picks can be saved"},409)}
 const now=Date.now();if(now>=start)return json({success:false,error:"Game is locked"},423);
 try{
  const membership=await db.prepare("SELECT status FROM memberships WHERE pool_id=? AND player_id=? LIMIT 1").bind(pool,player).first();if(!membership||membership.status!=="active")return json({success:false,error:"Active pool membership required"},403);
  const enabled=await db.prepare("SELECT 1 AS ok FROM pool_games WHERE pool_id=? AND game=? LIMIT 1").bind(pool,game).first();if(!enabled)return json({success:false,error:"This game is not enabled for the pool"},403);
  if(game==="Survivor"||game==="Game 33"){const existing=await db.prepare("SELECT event_id,selection FROM picks WHERE pool_id=? AND player_id=? AND game_type=? AND period_key=? LIMIT 1").bind(pool,player,game,period).first();if(existing&&String(existing.event_id)!==eventId)await db.prepare("DELETE FROM picks WHERE pool_id=? AND player_id=? AND game_type=? AND period_key=?").bind(pool,player,game,period).run()}
  if(game==="Confidence"&&b.points!=null){const points=Number(b.points);if(!Number.isInteger(points)||points<1)return json({success:false,error:"Confidence points must be a positive whole number"},400);const dup=await db.prepare("SELECT event_id FROM picks WHERE pool_id=? AND player_id=? AND game_type='Confidence' AND period_key=? AND points=? AND event_id<>? LIMIT 1").bind(pool,player,period,points,eventId).first();if(dup)return json({success:false,error:"That confidence value is already used"},409)}
 const id=crypto.randomUUID(),savedAt=new Date(now).toISOString();await db.prepare("INSERT INTO picks(id,pool_id,player_id,game_type,period_key,event_id,selection,points,saved_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(pool_id,player_id,game_type,period_key,event_id) DO UPDATE SET selection=excluded.selection,points=excluded.points,saved_at=excluded.saved_at").bind(id,pool,player,game,period,eventId,selection,b.points==null?null:Number(b.points),savedAt).run();return json({success:true,eventId,selection,savedAt,lockVerified:Boolean(feeds[game])})}catch{return json({success:false,error:"Pick save unavailable"},500)}
}