let memoryCache={};
const headers=(extra={})=>({"Content-Type":"application/json; charset=utf-8",...extra});
export async function onRequestGet(context){
 const key=String(context.env.SPORTS_GAME_ODDS_API_KEY||context.env.SPORTSGAMEODDS_API_KEY||context.env.SGO_API_KEY||"").trim();
 if(!key)return Response.json({success:false,code:"SECRET_MISSING",error:"Playmaker odds secret is not available to this deployment",diagnostic:{function:"playmaker-odds",secretDetected:false}},{status:503,headers:{"Cache-Control":"no-store"}});
 const q=new URL(context.request.url).searchParams,leagueID=q.get("leagueID")||"NFL,NCAAF,NBA,WNBA,MLB,NHL,NCAAB",limit=Math.min(Math.max(Number(q.get("limit")||20),1),100),bookmakerID=String(q.get("bookmakerID")||"").replace(/[^a-zA-Z0-9_,.-]/g,"").slice(0,180),oddIDs=String(q.get("oddIDs")||q.get("oddID")||"").replace(/[^a-zA-Z0-9_,.+-]/g,"").slice(0,1200),includeAltLines=q.get("includeAltLines")==="true",includeOpenCloseOdds=q.get("includeOpenCloseOdds")==="true",cacheKey=[leagueID,limit,bookmakerID,oddIDs,includeAltLines,includeOpenCloseOdds].join("|"),now=Date.now(),mem=memoryCache[cacheKey];
 if(mem&&now-mem.at<900000)return new Response(mem.body,{status:200,headers:headers({"Cache-Control":"public, max-age=600","X-LINKS-Odds-Cache":"memory"})});
 const edge=typeof caches!=="undefined"?caches.default:null,edgeReq=new Request(new URL("/__links_odds_cache/"+encodeURIComponent(cacheKey),context.request.url).toString());
 if(edge){const hit=await edge.match(edgeReq);if(hit){const body=await hit.text();memoryCache[cacheKey]={at:now,body};return new Response(body,{status:200,headers:headers({"Cache-Control":"public, max-age=600","X-LINKS-Odds-Cache":"edge"})})}}
 const upstream=new URL("https://api.sportsgameodds.com/v2/events");upstream.searchParams.set("leagueID",leagueID);upstream.searchParams.set("oddsAvailable","true");upstream.searchParams.set("limit",String(limit));upstream.searchParams.set("apiKey",key);upstream.searchParams.set("started","false");upstream.searchParams.set("ended","false");if(bookmakerID)upstream.searchParams.set("bookmakerID",bookmakerID);if(oddIDs)upstream.searchParams.set("oddIDs",oddIDs);if(includeAltLines)upstream.searchParams.set("includeAltLines","true");if(includeOpenCloseOdds)upstream.searchParams.set("includeOpenCloseOdds","true");
 try{const r=await fetch(upstream.toString(),{headers:{"Accept":"application/json","x-api-key":key}});let body=await r.text();
  if(r.ok){try{const parsed=JSON.parse(body),rows=Array.isArray(parsed?.data)?parsed.data:[],sample=rows.slice(0,3).map(e=>{const odds=Object.values(e?.odds||{}),ml=odds.filter(o=>String(o?.oddID||'').includes('-game-ml-'));return{eventID:e?.eventID||null,leagueID:e?.leagueID||null,teams:e?.teams||null,oddsCount:odds.length,moneylineCount:ml.length,moneylineIDs:ml.slice(0,6).map(o=>o?.oddID),bookmakerCounts:ml.slice(0,4).map(o=>Object.keys(o?.byBookmaker||{}).length)}});parsed.linksDiagnostic={leagueID,eventCount:rows.length,sample};body=JSON.stringify(parsed)}catch{}memoryCache[cacheKey]={at:now,body};if(edge)context.waitUntil(edge.put(edgeReq,new Response(body,{status:200,headers:headers({"Cache-Control":"public, max-age=900"})})));return new Response(body,{status:200,headers:headers({"Cache-Control":"public, max-age=600","X-LINKS-Odds-Cache":"provider"})})}
  if(r.status===429&&mem)return new Response(mem.body,{status:200,headers:headers({"Cache-Control":"public, max-age=60","X-LINKS-Odds-Cache":"stale-memory","X-LINKS-Odds-Warning":"provider-rate-limited"})});
  if(r.status===429)return Response.json({success:false,code:"RATE_LIMITED",error:"Live odds provider rate limit reached. Pool picks and scores remain available; Playmaker odds will retry after the provider window resets."},{status:429,headers:{"Cache-Control":"no-store"}});
  return new Response(body,{status:r.status,headers:headers({"Cache-Control":"no-store","X-LINKS-Odds-Secret":"present"})});
 }catch(e){if(mem)return new Response(mem.body,{status:200,headers:headers({"Cache-Control":"public, max-age=60","X-LINKS-Odds-Cache":"stale-memory"})});return Response.json({success:false,error:"Odds provider unavailable"},{status:502,headers:{"Cache-Control":"no-store"}})}
}