// Original LINKS fiction. All suspects, events, and locations are invented.
export const ROLES=[
 {id:'heir',title:'The Heir',name:'Rowan Vale',intro:'The family name opens every door. The family debt keeps you awake.',secret:'You quietly sold part of the family collection to cover a failed investment.',motive:'Adrian planned to remove you from the will after discovering the missing collection.'},
 {id:'curator',title:'The Curator',name:'Ellis Ward',intro:'You know the history of every object in this house—and which histories are invented.',secret:'The centerpiece of Adrian’s collection is a copy. You signed the authentication.',motive:'Adrian had proof that you authenticated a counterfeit and intended to expose it.'},
 {id:'partner',title:'The Business Partner',name:'Morgan Shaw',intro:'You helped build the fortune. Adrian took the credit.',secret:'You moved company money to keep a project alive without Adrian’s permission.',motive:'Adrian was going to report your unauthorized transfers and leave you responsible for the losses.'},
 {id:'journalist',title:'The Journalist',name:'Alex Reed',intro:'You came for an interview. You stayed because the real story was behind a locked door.',secret:'You paid for a stolen recording that would destroy someone’s career.',motive:'Adrian intended to publish evidence that your award-winning investigation relied on a fabricated source.'},
 {id:'doctor',title:'The Family Doctor',name:'Jordan Bell',intro:'You have kept this family’s confidences for years. Tonight, confidentiality has a price.',secret:'You signed a confidential statement at Adrian’s request without checking its contents.',motive:'Adrian planned to use your signed false statement to protect himself and ruin your reputation.'},
 {id:'manager',title:'The Estate Manager',name:'Casey Finch',intro:'You run this house. You know which doors stick and which guests never say thank you.',secret:'You copied a sealed family document for someone outside the estate.',motive:'Adrian discovered you sold a private family document and planned to dismiss and publicly accuse you.'},
 {id:'performer',title:'The Evening’s Performer',name:'Riley Cross',intro:'Your voice fills the room. Adrian’s influence decides whether anyone hears it again.',secret:'You used a different identity before your career began.',motive:'Adrian had obtained records of your former identity and threatened to destroy the career you rebuilt.'},
 {id:'architect',title:'The Architect',name:'Sam Mercer',intro:'You restored Blackthorn Manor. You wish you could repair what happened inside it.',secret:'You concealed an expensive mistake in the restoration accounts.',motive:'Adrian planned to release the altered restoration accounts with your signature on every page.'}
];
export const ROOMS=[{id:'study',name:'The Study',art:'study'},{id:'conservatory',name:'The Conservatory',art:'conservatory'},{id:'gallery',name:'The Gallery',art:'gallery'},{id:'dining',name:'The Dining Room',art:'dining'},{id:'gate',name:'The Gatehouse',art:'gate'},{id:'music',name:'The Music Room',art:'music'}];
export const METHODS=[{id:'object',label:'A fatal blow',object:'bronze presentation clock',detail:'A fatal blow from the missing bronze presentation clock',scene:null},{id:'drink',label:'A tampered drink',object:'tampered drink',detail:'A deliberately contaminated drink',scene:null},{id:'fall',label:'A staged accident',object:'staged fall',detail:'A deliberate push from the upper gallery disguised as an accident',scene:'gallery'}];
export const CHAPTERS=[
 {title:'A Toast Interrupted',label:'Prologue',story:'Adrian Vale has invited a small circle to Blackthorn Manor for the unveiling of his restored collection. At dinner, he raises a glass. “Before midnight, one of you will finally tell the truth.” Nobody laughs. A storm cuts the road to the village. Minutes later, the estate bell rings three times. Adrian is dead. The constable, stranded on the far side of the flooded bridge, asks you to preserve the scene. Every guest had a reason to fear midnight.'},
 {title:'The Missing Minutes',label:'Act I',story:'The grandfather clock is still ticking, but the dinner conversation has stopped. A servant remembers an empty chair. Someone has changed their account of the evening. Search the house, compare what you remember, and decide whose story needs a second look.'},
 {title:'Beyond the Locked Door',label:'Act II',story:'The locked doors were supposed to keep strangers out. They also kept secrets in. An entry log survives the storm. A witness at the gate remembers more than the guests expected. The circle of suspicion begins to close.'},
 {title:'Voices in the Dark',label:'Act III',story:'A recording made for tonight’s performance captures something nobody meant to preserve: the ordinary sounds of people exactly where they claim to have been. Listen carefully. An innocent detail may matter more than an impressive accusation.'},
 {title:'The Midnight Envelope',label:'Act IV',story:'The envelope Adrian meant to open at midnight has been found. Its contents expose motives, not just movements. Nearly everyone has lied about something. Only one person had no verified alibi when Adrian died. Build a case from evidence—not from who tells the best story.'}
];
export function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
const names=ps=>ps.map(p=>p.character.name).join(', ');
export function buildCase(s){
 if(s.mode==='together'||(!s.mode&&Object.keys(s.players).length<4)){
  const cast={players:Object.fromEntries(Array.from({length:6},(_,i)=>['suspect'+i,{id:'suspect-'+i,name:'Case suspect'}])),previousCulprit:s.previousCulprit,previousMethod:s.previousMethod};
  buildCase(cast);s.cooperative=true;s.suspects=cast.players;s.case=cast.case;s.published=[];
  for(const p of Object.values(s.players))Object.assign(p,{character:{name:p.name,title:'Investigator',intro:'You were asked to investigate Blackthorn Manor.',secret:'Your notebook is private. Share discoveries with your partner when you are ready.',motive:'Find the truth.'},alibi:'You are an investigator, not a suspect.',searched:{},shared:[],notes:'',accusation:null,score:0});
  return;
 }
 s.cooperative=false;delete s.suspects;
 const seats=Object.keys(s.players),roles=shuffle(ROLES).slice(0,seats.length);seats.forEach((seat,i)=>{Object.assign(s.players[seat],{character:roles[i],searched:{},shared:[],notes:'',accusation:null,score:0})});
 const eligible=seats.filter(x=>s.players[x].id!==s.previousCulprit),killer=shuffle(eligible.length?eligible:seats)[0],innocents=shuffle(seats.filter(x=>x!==killer)),groups=[[],[],[]];innocents.forEach((x,i)=>groups[i%3].push(x));
 const method=shuffle(METHODS.filter(m=>m.id!==s.previousMethod))[0],scene=method.scene?ROOMS.find(r=>r.id===method.scene):shuffle(ROOMS.slice(0,3))[0],time=shuffle(['9:12–9:18 PM','9:24–9:30 PM','9:36–9:42 PM'])[0],object=method.object;
 const alibis=['in the dining room with the caterer','at the gatehouse sheltering with the driver','in the music room recording the rehearsal'];groups.forEach((g,i)=>g.forEach(x=>s.players[x].alibi='During '+time+', you were '+alibis[i]+'. This is true.'));
 s.players[killer].alibi='Your prepared story: during '+time+', you were in the dining room. This is false. You may bluff, but you cannot change the game’s evidence.';
 const evidence=[
 {id:'window',chapter:1,room:scene.id,title:'The Last Call',kind:'Verified evidence',text:'A telephone call from Adrian ended just before '+time+'. The constable confirms that the attack occurred during that six-minute window. The scene was '+scene.name.toLowerCase()+'. This is the only time window that matters.',eliminates:[]},
 {id:'dinner',chapter:1,room:'dining',title:'The Caterer’s Account',kind:'Verified alibi',text:'The caterer and a continuous dining-room camera independently place '+names(groups[0].map(x=>s.players[x]))+' at the table throughout '+time+'. Those guests could not have reached the scene. Nobody else has a verified dining-room alibi.',eliminates:groups[0].map(x=>s.players[x].id)},
 {id:'gate',chapter:2,room:'gate',title:'The Gatehouse Log',kind:'Verified alibi',text:'The driver’s time-stamped dash camera places '+names(groups[1].map(x=>s.players[x]))+' inside the gatehouse throughout '+time+'. The locked exterior gate and uninterrupted recording rule out leaving unnoticed.',eliminates:groups[1].map(x=>s.players[x].id)},
 {id:'object',chapter:2,room:'gallery',title:'The Empty Plinth',kind:'Verified evidence',text:'A '+object+' is missing from its display. The constable confirms it was the object recovered at the scene. All invited guests had access to the display before dinner; access alone does not identify the murderer.',eliminates:[]},
 {id:'recording',chapter:3,room:'music',title:'The Unbroken Recording',kind:'Verified alibi',text:'A rehearsal recording and its synchronized video place '+names(groups[2].map(x=>s.players[x]))+' in the music room throughout '+time+'. The recording is continuous. Those guests could not have carried out the attack.',eliminates:groups[2].map(x=>s.players[x].id)},
 {id:'letter',chapter:3,room:'conservatory',title:'The Unsent Letter',kind:'Context',text:'A torn note reads: “You do not get to choose who I become after tonight.” It is unsigned. The paper came from the guest stationery supplied to everyone. It proves resentment, not identity.',eliminates:[]},
 {id:'envelope',chapter:4,room:'study',title:'The Midnight Envelope',kind:'Motive file',text:'Adrian had prepared a dossier on every guest. '+seats.map(x=>s.players[x].character.name+': '+s.players[x].character.motive).join(' '),eliminates:[]},
 {id:'reconstruction',chapter:4,room:scene.id,title:'The Constable’s Reconstruction',kind:'Verified evidence',text:'The attack happened in '+scene.name.toLowerCase()+' during '+time+', using the '+object+'. The three verified alibis cover different guests. Compare all three: one invited guest is absent from every verified account. Rumors and private secrets do not override those records.',eliminates:[]}
 ];
 // Hard case: players must normalize independent clocks before comparing alibis.
 const start=Number(time.slice(2,4)),offsets=shuffle([4,7,11]),stamp=n=>'21:'+String(n).padStart(2,'0');
 const sources=[['dinner',0,'Dining-room camera'],['gate',1,'Gatehouse recorder'],['recording',2,'Music-room recorder']];
 sources.forEach(([id,i,source])=>{const e=evidence.find(e=>e.id===id);e.kind='Time-stamped record';e.title=['Contact Sheet 04','Gatehouse Interview','Rehearsal Footage'][i];e.text=source+' — device time '+stamp(start+offsets[i])+' to '+stamp(start+6+offsets[i])+'. The following people remain in view for the entire clip: '+names(groups[i].map(x=>s.players[x]))+'. The footage is continuous. Compare this device’s clock with the reference-time records before deciding what it proves.';e.inspect=[{label:'Read the device stamp',text:'Local display: '+stamp(start+offsets[i])+'–'+stamp(start+6+offsets[i])+'. The clip has no gaps.'},{label:'Examine the visible guests',text:names(groups[i].map(x=>s.players[x]))+'. Their faces are identifiable. No other guest appears in this clip.'},{label:'Inspect the recording seal',text:'Original recording, verified by the constable. Its clock has not been corrected.'}];});
 const calibrations=offsets.map((offset,i)=>({id:'clock-'+i,chapter:i===0?2:3,room:['study','gate','music'][i],title:['Camera Service Slip','Dispatch Time Check','Sound Engineer’s Slate'][i],kind:'Clock reference',text:['Dining-room camera','Gatehouse recorder','Music-room recorder'][i]+' clock test. At reference time 21:00, the device displayed '+stamp(offset)+'. Both readings were taken at the same instant. No adjustment was made afterward. The same offset applies to the full evening.',inspect:[{label:'Read the reference clock',text:'Police reference clock: 21:00. This clock is accurate.'},{label:'Read the device clock',text:'Device reading at that same instant: '+stamp(offset)+'.'},{label:'Check the handwritten note',text:'“Do not reset until after tonight’s event.” Signed by the technician.'}],eliminates:[]}));
 evidence.push(...calibrations);
 // A genuine but earlier clip includes the culprit; names alone cannot solve the case.
 const earlierStart=start-10+offsets[0],earlierEnd=start-4+offsets[0],decoyGuests=[s.players[killer],s.players[innocents[0]]];
 evidence.push({id:'earlier-clip',chapter:1,room:'gallery',title:'Contact Sheet 03',kind:'Time-stamped record',text:'Dining-room camera — device time '+stamp(earlierStart)+' to '+stamp(earlierEnd)+'. The following guests remain visible through the entire clip: '+names(decoyGuests)+'. The clip has no gaps. The device retained its original clock setting.',inspect:[{label:'Read the device stamp',text:'Local display '+stamp(earlierStart)+'–'+stamp(earlierEnd)+'.'},{label:'Identify the guests',text:names(decoyGuests)+'. Both remain in frame.'},{label:'Inspect the source mark',text:'DINING CAMERA. Same recording device as Contact Sheet 04.'}],eliminates:[]});
 const forensic=evidence.find(e=>e.id==='object');forensic.title='The Forensic Summary';forensic.text=method.id==='object'?'The bronze presentation clock is missing from its display. Its damage matches the object recovered at the scene. The constable rules out an accident. Every guest had access to the display before dinner.':method.id==='drink'?'The laboratory confirms that Adrian’s drink was deliberately contaminated. A partial scene recording shows an unidentified visitor tampering with the freshly poured glass during the incident window. The image cannot identify a face. The drink was not prepared earlier.':'A partial gallery recording shows an unidentified visitor pushing Adrian from the upper gallery during the incident window. It was not an accidental fall. The visitor’s face is outside the camera’s view.';
 evidence.find(e=>e.id==='window').text='Adrian’s final call and the scene recording place the criminal act during '+time+'. The perpetrator was physically in '+scene.name.toLowerCase()+' during that interval. The recording cannot identify the perpetrator. These times are synchronized to the police reference clock.';
 evidence.find(e=>e.id==='reconstruction').text='The constable confirms the object was the '+object+', and the scene was '+scene.name.toLowerCase()+'. All three recording devices kept their original clock settings. A recorded time is not necessarily the real time. Use the clock-reference documents and the last call to build a single timeline. A secret is a motive, not proof.';
 evidence.find(e=>e.id==='window').inspect=[{label:'Inspect call metadata',text:'Network time is synchronized. Adrian was alive just before '+time+'.'},{label:'Read the constable’s note',text:'The attack took place during '+time+'. Keep this as your reference window.'},{label:'Examine the location note',text:'Adrian was found in '+scene.name.toLowerCase()+'.'}];
 for(const e of evidence)if(!e.inspect)e.inspect=[{label:'Examine the document',text:e.text},{label:'Check its provenance',text:e.kind==='Context'?'Unsigned. Treat as context, not a verified alibi.':'Logged for the constable. Preserve the original wording.'}];
 s.case={killer,scene,time,object,method,evidence};s.published=[];
 if(solve(s).length!==1||solve(s)[0]!==s.players[killer].id)throw Error('Case validation failed');
}
export function solve(s){const eliminated=new Set(s.case.evidence.flatMap(e=>e.eliminates));return Object.values(s.suspects||s.players).map(p=>p.id).filter(id=>!eliminated.has(id))}
export function begin(s,now){buildCase(s);s.phase='briefing';s.chapter=0;s.deadline=now+180000;s.phaseStarted=now;s.pausedAt=null;}
export function finish(s){s.phase='ended';s.deadline=0;const killer=(s.suspects||s.players)[s.case.killer],votes=Object.values(s.players).filter(p=>p.accusation?.suspect===killer.id).length;s.caught=votes>Object.keys(s.players).length/2;for(const [seat,p] of Object.entries(s.players)){p.score=!s.cooperative&&seat===s.case.killer?(s.caught?0:500):(p.accusation?.suspect===killer.id?500:0)+(p.accusation?.scene===s.case.scene.id?100:0)+(p.accusation?.object===s.case.object?100:0)} s.previousCulprit=killer.id;s.previousMethod=s.case.method.id;}
export function next(s,now){
 for(const p of Object.values(s.players))p.chapterReady=false;
 if(s.phase==='briefing'){s.phase='investigate';s.chapter=1}
 else if(s.phase==='investigate'){for(const e of s.case.evidence.filter(e=>e.chapter<=s.chapter))if(!s.published.includes(e.id))s.published.push(e.id);if(s.chapter<4)s.chapter++;else s.phase='accuse'}
 else if(s.phase==='accuse'){finish(s);return}
 s.phaseStarted=now;s.deadline=now+(s.phase==='accuse'?240000:s.minutes===45?570000:420000);
}
export function advance(s,now){if(!s.guided&&!s.pausedAt&&['briefing','investigate','accuse'].includes(s.phase)&&now>=s.deadline){next(s,now);return true}return false}
export function view(s,seat,now,display=false){
 const cast=s.suspects||s.players,player=s.players[seat],end=s.phase==='ended',c=s.case,discovered=player?Object.values(player.searched||{}).flat():[],publicClues=c?c.evidence.filter(e=>s.published.includes(e.id)):[];
 const clue=e=>({id:e.id,title:e.title,kind:e.kind,text:e.text,inspect:e.inspect,chapter:e.chapter,room:e.room});
 return {code:s.code,game:s.game,mode:s.mode,guided:!!s.guided,cooperative:!!s.cooperative,phase:s.phase,chapter:s.chapter||0,minutes:s.minutes,serverNow:now,deadline:s.deadline,paused:!!s.pausedAt,pausedAt:s.pausedAt,host:seat===s.owner&&!display,display,
 players:Object.entries(s.players).map(([id,p])=>({id:p.id,name:p.name,ready:p.ready,chapterReady:!!p.chapterReady,you:!display&&id===seat,character:c?{name:p.character.name,title:p.character.title,intro:p.character.intro}:null,...(end?{score:p.score,accusation:p.accusation?.suspect||null,killer:id===c.killer}:{})})),
 suspects:c?Object.values(cast).map(p=>({id:p.id,name:s.cooperative?'Case suspect':p.name,character:{name:p.character.name,title:p.character.title,intro:p.character.intro}})):[],
 chapterInfo:s.phase==='lobby'?null:s.cooperative&&s.chapter===0?{...CHAPTERS[0],story:CHAPTERS[0].story+' You are investigating this case together. None of you are suspects. Examine the six guests and compare your discoveries.'}:CHAPTERS[s.chapter||0],rooms:ROOMS,publicClues:publicClues.map(clue),
 discovered:!display&&c?c.evidence.filter(e=>discovered.includes(e.id)).map(clue):[],searched:!display?player?.searched?.[s.chapter]||[]:[],notes:!display?player?.notes||'':'',objects:!display&&c&&s.phase==='investigate'?c.evidence.filter(e=>e.chapter<=s.chapter).map(e=>({id:e.id,title:e.title,room:e.room,collected:discovered.includes(e.id)||s.published.includes(e.id)})):[],
 privateRole:!display&&c&&player?{...player.character,guilty:!s.cooperative&&seat===c.killer,alibi:player.alibi,...(seat===c.killer?{truth:'You confronted Adrian in '+c.scene.name.toLowerCase()+' during '+c.time+'. The '+c.object+' was used in the attack. '+player.character.motive+' Your goal is to avoid a majority accusation. You may lie in conversation; the verified evidence cannot be altered.'}:{truth:s.cooperative?'Your team are investigators. None of you are suspects. Search the manor, share clues, correct the device clocks, and identify which of the six guests has no verified alibi. Each investigator submits their own conclusion.':'You are innocent of the murder. Your secret may make you look suspicious. Find the murderer using the verified alibis.'})}:null,
 accusation:!display?player?.accusation||null:null,objectsToChoose:METHODS.map(m=>m.object),accusationsReceived:Object.values(s.players).filter(p=>p.accusation).length,
 ...(end?{ending:{caught:s.caught,culprit:c?cast[c.killer].character.name:'',playerName:s.cooperative?'Case suspect':c?cast[c.killer].name:'',story:'Adrian’s midnight revelation never came. '+cast[c.killer].character.name+' confronted him in '+c.scene.name.toLowerCase()+'. '+cast[c.killer].character.motive+' The confrontation ended in murder during '+c.time+'. The '+c.object+' was left behind. The dining-room camera, gatehouse log, and rehearsal recording cleared every other guest. The dining-room story offered by the murderer had no witness to support it.',evidence:c.evidence.map(clue)}}:{}),
 ...(seat===s.owner&&!display?{displayKey:s.displayKey}:{})};
}
