import {balancedCategories} from './trivia-category-balance.js';
import {STARTER,CATEGORIES} from './trivia-night.js';
import {loadGameQuestions,completeQuestionBank} from './trivia-provider.js';
export const LADDER=[100,200,300,500,1000,2000,4000,8000,16000,32000,64000,125000,250000,500000,1000000];
export function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=crypto.getRandomValues(new Uint32Array(1))[0]%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
export const questionText=q=>q.text.trim().toLowerCase().replace(/\s+/g,' ');
export async function loadBank(env,exclude=[],excludeTexts=[]){
 const loaded=await loadGameQuestions({env,categories:CATEGORIES,backup:shuffle(STARTER),exclude,perGroup:6}),ids=new Set(exclude),texts=new Set(excludeTexts);let repeated=false;
 const questions=['easy','medium','hard'].flatMap(d=>{
  const pool=completeQuestionBank(loaded.questions.filter(q=>q.difficulty===d),shuffle(STARTER.filter(q=>q.difficulty===d)),{minimum:6});
  const unseen=pool.filter(q=>!ids.has(q.id)&&!texts.has(questionText(q)));
  if(unseen.length>=6)return shuffle(unseen);
  const backup=shuffle(STARTER.filter(q=>q.difficulty===d&&!ids.has(q.id)&&!texts.has(questionText(q))));
  const fresh=completeQuestionBank(unseen,backup,{minimum:6});if(fresh.length>=6)return fresh;
  repeated=true;const older=shuffle([...pool,...STARTER.filter(q=>q.difficulty===d)]).sort((a,b)=>Math.max(exclude.indexOf(a.id),excludeTexts.indexOf(questionText(a)))-Math.max(exclude.indexOf(b.id),excludeTexts.indexOf(questionText(b))));
  return completeQuestionBank(fresh,older,{minimum:6});
 });
 return {questions,notice:repeated?'Fresh questions are limited. Older questions may return after the unused questions.':loaded.notice||(!env.TRIVIA_API_KEY?'Using the backup question library.':'')};
}
export function prepareTurn(s,now){s.level=0;s.earned=0;s.safe=0;s.used=[];s.removed=[];s.votes={};s.poll=null;s.outcome=null;const seen=new Set(s.seen||[]),texts=new Set(s.seenTexts||[]);const used=q=>seen.has(q.id)||texts.has(questionText(q));s.deck=['easy','medium','hard'].flatMap(d=>{const qs=s.bank.filter(q=>q.difficulty===d);return [...balancedCategories(qs.filter(q=>!used(q))),...balancedCategories(qs.filter(used))].slice(0,5).map(q=>{const order=shuffle([0,1,2,3]);return {...q,answers:order.map(i=>q.answers[i]),correct:order.indexOf(q.correct)}})});if(s.deck.length!==15)throw Error('Question library unavailable.');s.phase='intro';s.deadline=now+5000;s.phaseId++;}
function openQuestion(s,now){s.phase='question';s.deadline=now+(s.mode==='duel'?25000:60000);s.phaseId++;s.removed=[];s.votes={};s.poll=null;s.selected=null;const q=s.deck[s.level],text=questionText(q);s.seen=[...(s.seen||[]).filter(id=>id!==q.id),q.id].slice(-1500);s.seenTexts=[...(s.seenTexts||[]).filter(t=>t!==text),text].slice(-1500)}
function finishTurn(s,reason){s.players[s.order[s.turn]].score=s.earned;s.outcome=reason;s.phase='turnEnd';s.deadline=0;s.phaseId++;}
export function advance(s,now){if(s.mode==='duel')return advanceDuel(s,now);if(!s.deadline||now<s.deadline)return false;if(s.phase==='intro')openQuestion(s,now);else if(s.phase==='poll'){s.poll=[0,1,2,3].map(i=>Object.values(s.votes).filter(v=>v===i).length);s.phase='question';s.deadline=now+s.remaining;s.phaseId++}else if(s.phase==='question'){s.selected=null;s.correct=false;s.outcome='Time ran out';s.phase='reveal';s.deadline=now+6000;s.phaseId++}else if(s.phase==='reveal'){if(!s.correct){s.earned=s.safe;finishTurn(s,s.outcome||'The ladder ends here')}else{s.earned=LADDER[s.level];if(s.level===4||s.level===9)s.safe=s.earned;if(s.level===14)finishTurn(s,'ONE MILLION POINTS');else{s.phase='decision';s.deadline=0;s.phaseId++}}}return true}
export function act(s,seat,b,now){if(s.mode==='duel')return actDuel(s,seat,b,now);const active=s.order?.[s.turn],q=s.deck?.[s.level];if(b.game!==s.game||b.phaseId!==s.phaseId)throw Error('This screen has changed. Please try again.');
 if(b.action==='vote'){if(s.phase!=='poll'||seat===active||Object.hasOwn(s.votes,seat)||!Number.isInteger(b.choice)||b.choice<0||b.choice>3||s.removed.includes(b.choice))throw Error('The room vote is closed.');s.votes[seat]=b.choice;return}
 if(seat!==active)throw Error('It is another player’s turn.');
 if(b.action==='answer'){if(s.phase!=='question'||!Number.isInteger(b.choice)||b.choice<0||b.choice>3||s.removed.includes(b.choice))throw Error('Choose an available answer.');s.selected=b.choice;s.correct=b.choice===q.correct;s.outcome=s.correct?'Correct answer':'Incorrect answer';s.phase='reveal';s.deadline=now+6000;s.phaseId++;return}
 if(b.action==='bank'){if(!['question','decision'].includes(s.phase))throw Error('Wait for the current screen.');finishTurn(s,'Banked the points');return}
 if(b.action==='continue'){if(s.phase!=='decision')throw Error('Wait for the reveal.');s.level++;openQuestion(s,now);return}
 if(b.action==='lifeline'){if(s.phase!=='question'||!['half','room','swap'].includes(b.kind)||s.used.includes(b.kind))throw Error('That lifeline is unavailable.');if(b.kind==='room'&&s.order.length<2)throw Error('Ask the Room needs another player.');
  if(b.kind==='half')s.removed=shuffle([0,1,2,3].filter(i=>i!==q.correct)).slice(0,2);
  if(b.kind==='room'){s.remaining=Math.max(1000,s.deadline-now);s.phase='poll';s.deadline=now+15000;s.phaseId++;s.votes={}}
  if(b.kind==='swap'){const ids=new Set(s.deck.map(x=>x.id)),replacement=shuffle(s.bank.filter(x=>x.difficulty===q.difficulty&&!ids.has(x.id)))[0];if(!replacement)throw Error('No replacement question is available.');const order=shuffle([0,1,2,3]);s.deck[s.level]={...replacement,answers:order.map(i=>replacement.answers[i]),correct:order.indexOf(replacement.correct)};openQuestion(s,now)}
  s.used.push(b.kind);return;
 }throw Error('Unknown game action.');}
export function view(s,seat,now,display=false){const active=s.order?.[s.turn],q=s.deck?.[s.level],revealed=s.phase==='reveal'||s.phase==='decision',me=s.players[seat],duel=s.mode==='duel',d=s.duel?.[seat],removed=duel?(display?[]:d?.removed||[]):s.removed||[];return {code:s.code,mode:s.mode||'hotseat',game:s.game,phase:s.phase,phaseId:s.phaseId,serverNow:now,deadline:s.deadline,host:!display&&seat===s.owner,display,displayKey:!display&&seat===s.owner?s.displayKey:undefined,active:!display&&(duel?!!d&&!d.out&&!d.locked:seat===active),personalResult:duel&&!display&&d?.out?{reason:d.reason||'Your run is over',answer:d.lastAnswer||null}:null,activeName:duel?'HEAD TO HEAD':s.players[active]?.name,turn:s.turn||0,level:s.level||0,earned:duel?d?.earned||0:s.earned||0,safe:duel?d?.safe||0:s.safe||0,ladder:LADDER,used:duel?d?.used||[]:s.used||[],removed,poll:s.poll,notice:s.notice||'',voted:!!me&&Object.hasOwn(s.votes||{},seat),votesReceived:Object.keys(s.votes||{}).length,outcome:s.outcome,players:Object.entries(s.players).map(([id,p])=>({name:p.name,ready:p.ready,score:duel?s.duel?.[id]?.earned||0:p.score,you:!display&&id===seat,active:id===active,locked:duel?!!s.duel?.[id]?.locked:undefined,out:duel?!!s.duel?.[id]?.out:undefined})),question:(!duel||display||!d?.out)&&['question','poll','reveal','decision'].includes(s.phase)&&q?{text:q.text,answers:q.answers.map((a,i)=>removed.includes(i)?null:a),difficulty:q.difficulty,...(revealed?{correct:q.correct,selected:duel?d?.choice:s.selected,source:q.source}:{})}:null};}
export function prepareDuel(s,now){prepareTurn(s,now);s.duel=Object.fromEntries(s.order.map(id=>[id,{earned:0,safe:0,out:false,locked:false,choice:null,used:[],removed:[]}]))}
function advanceDuel(s,now){if(!s.deadline||now<s.deadline)return false;if(s.phase==='intro')openQuestion(s,now);else if(s.phase==='question'){for(const d of Object.values(s.duel)){if(d.out)continue;if(d.choice===s.deck[s.level].correct){d.earned=LADDER[s.level];if(s.level===4||s.level===9)d.safe=d.earned}else{d.earned=d.safe;d.out=true;d.reason=d.choice===null?'Time ran out':'Incorrect answer';d.lastAnswer=s.deck[s.level].answers[s.deck[s.level].correct]}}s.phase='reveal';s.deadline=now+6000;s.phaseId++}else if(s.phase==='reveal'){if(s.level===14||Object.values(s.duel).every(d=>d.out)){s.phase='ended';s.deadline=0;s.phaseId++}else{s.level++;for(const d of Object.values(s.duel)){d.choice=null;d.locked=false;d.removed=[]}openQuestion(s,now)}}return true}
function actDuel(s,seat,b,now){const d=s.duel?.[seat];if(b.game!==s.game||b.phaseId!==s.phaseId||s.phase!=='question'||!d||d.out||d.locked)throw Error('This answer window is locked.');if(b.action==='bank'){d.out=true;d.locked=true;d.reason='Points banked';return}if(b.action==='lifeline'&&b.kind==='half'&&!d.used.includes('half')){d.used.push('half');d.removed=shuffle([0,1,2,3].filter(i=>i!==s.deck[s.level].correct)).slice(0,2);return}if(b.action==='answer'&&Number.isInteger(b.choice)&&b.choice>=0&&b.choice<4&&!d.removed.includes(b.choice)){d.choice=b.choice;d.locked=true;return}throw Error('Choose an available answer.');}
