export const escapeEmail=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function emailConfig(env){return {key:String(env.RESEND_API_KEY||env.RESEND_KEY||'').trim(),from:String(env.RESEND_FROM_EMAIL||env.LINKS_EMAIL_FROM||env.EMAIL_FROM||'noreply@linkspickempools.com').trim()}}
export function poolEmail({base='https://linkspickempools.com',poolName,poolCode,name='',commissioner=false,inviteUrl='',rules='',games=['nfl']}){
 base=new URL(base).origin;const e=escapeEmail,login=base+'/new-build/pool-login.html?code='+encodeURIComponent(poolCode),url=inviteUrl||login;
 const title=inviteUrl?"You're invited to "+poolName:commissioner?'Your pool is ready: '+poolName:'Welcome to '+poolName;
 const sections=[['Welcome to LINKS',`LINKS brings your pool’s picks, live scores, weekly results, and season standings together. ${name?'Welcome, '+name+'. ':''}Use the button below to ${inviteUrl?'create your player name and password in this pool':'sign in to this pool with your player name and password'}. Your pool code is ${poolCode}.`],['Make your NFL picks','Choose one team in each matchup and enter your combined-score tiebreaker. Lock My Picks freezes your card; you may unlock and change it before the first kickoff of that week. Closing the optional Playmaker popup does not unlock your card. Follow the countdown on the Picks page.'],['Follow the week','Live Scores follows the action. Compare Picks, Picks That Matter, and Projected reveal other players’ picks only after the first kickoff of the selected week. Completed weeks remain available. Use the week selector to review history; the current week advances when all games are final.'],['Results and projections','Weekly Standings shows wins and losses and the winner when the week is complete. Year Standings combines final-game results across weeks. Projected estimates the chance of finishing first or tied first before the score tiebreaker; it is not a guarantee. Missing game probabilities are labeled.'],['Keep a copy','Print My Picks opens your current week’s card with your picks and tiebreaker. Use Print / Save to keep a copy.'],['Optional Playmaker','After locking your picks, you can choose teams to research in Playmaker. It is optional and does not change your official pool picks.']];
 if(commissioner)sections.push(['Your commissioner controls','Open ADMIN from NFL Pick’em. Save your commissioner contact email and pool rules; invite players by email and review individual send results; add players and manage Active/Pending access; reset a player’s temporary password; select a week to review results and make a targeted result, pick, or tiebreaker correction; finalize the winner after games finish. Back to Pool returns to your pool.'],['Invitations and email delivery','In Players & Invites, enter addresses separated by commas or new lines. Each invitation includes a private link to the correct pool. A created link does not mean an email was sent: review the delivery status for each address. Email accepted by the provider is not a guarantee of inbox delivery; recipients should also check spam.'],['Commissioner care','Review the selected player, week, and matchup before saving corrections. The first-kickoff privacy rule still applies to shared pick pages. Pool entry arrangements are handled by your commissioner; LINKS does not collect your pool’s entry pot.']);
 else sections.push(['Your commissioner','Your commissioner manages pool rules, invitations, player access, and corrections. Contact them if you need access or a correction. Only the commissioner can use Admin.']);
 if(rules)sections.push(['Your pool rules',rules]);
 const text=title+'\nPool code: '+poolCode+'\n'+url+'\n\n'+sections.map(([h,t])=>h+'\n'+t).join('\n\n');
 const html='<!doctype html><html><body style="margin:0;background:#061019;font-family:Arial,sans-serif;color:#e9eff4"><table role="presentation" width="100%"><tr><td align="center" style="padding:20px 12px"><table role="presentation" width="100%" style="max-width:640px;background:#0d1b26;border:1px solid #345066;border-radius:14px"><tr><td style="padding:24px"><img src="'+base+'/new-build/assets/ChatGPT%20Image%20Sep%2022%2C%202026%2C%2007_35_27%20PM.png" alt="LINKS Pickem Pools" width="140" style="display:block;width:140px;height:auto;margin:0 auto 24px"><h1 style="font-size:26px;color:#edc466">'+e(title)+'</h1><p>POOL CODE: <b>'+e(poolCode)+'</b></p><p style="margin:24px 0"><a href="'+e(url)+'" style="display:inline-block;padding:14px 22px;background:#edc466;color:#08131b;text-decoration:none;border-radius:8px;font-weight:bold">'+(inviteUrl?'JOIN THIS POOL':'OPEN MY POOL')+'</a></p>'+sections.map(([h,t])=>'<h2 style="font-size:18px;color:#edc466;margin-top:26px">'+e(h)+'</h2><p style="line-height:1.65;white-space:pre-line">'+e(t)+'</p>').join('')+'<p style="font-size:12px;color:#adbdc9;margin-top:30px">LINKS · PICKS. POOLS. PEOPLE.<br>If the button does not work, open:<br><a style="color:#edc466;word-break:break-all" href="'+e(url)+'">'+e(url)+'</a></p></td></tr></table></td></tr></table></body></html>';
 return {subject:title,html,text};
}
export async function sendPoolEmail(env,to,content,key){const cfg=emailConfig(env);if(!cfg.key)return {sent:false,error:'Email service is not configured.'};try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+cfg.key,'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},body:JSON.stringify({from:cfg.from.includes('<')?cfg.from:'LINKS Pickem Pools <'+cfg.from+'>',to:[to],...content}),signal:AbortSignal.timeout(15000)}),j=await r.json();return r.ok&&j.id?{sent:true,id:j.id}:{sent:false,error:String(j.message||'Email provider rejected the message.').slice(0,250)}}catch{return {sent:false,error:'Email service could not be reached. Pool access is unaffected.'}}}
