// Original LINKS prompt bank. Aliases are accepted guesses; forbidden terms are clue-only.
export const BANK = [
['Football stadium','football,stadium,field','Sports'],['Basketball hoop','basketball,hoop,basket','Sports'],['Golf cart','golf,cart,course','Sports'],['Race car','race,car,driver','Sports'],['Bowling alley','bowling,alley,pins','Sports'],['Referee','referee,whistle,penalty','Sports'],['Touchdown','touchdown,football,score','Sports'],['Ice hockey','ice,hockey,puck','Sports'],
['Popcorn','popcorn,corn,movie','Food'],['Birthday cake','birthday,cake,candles','Food'],['Hot dog','hot,dog,bun','Food'],['Ice cream','ice,cream,frozen','Food'],['Pancakes','pancake,syrup,breakfast','Food'],['Pizza','pizza,cheese,slice','Food'],['Spaghetti','spaghetti,pasta,noodle','Food'],['Watermelon','watermelon,melon,fruit','Food'],
['Roller coaster','roller,coaster,ride','Places'],['Airport','airport,plane,flight','Places'],['Library','library,book,read','Places'],['Aquarium','aquarium,fish,water','Places'],['Movie theater','movie,theater,cinema','Places'],['Fire station','fire,station,truck','Places'],['Swimming pool','swimming,pool,water','Places'],['Zoo','zoo,animal,cage','Places'],
['Toothbrush','toothbrush,teeth,brush','Everyday'],['Umbrella','umbrella,rain,wet','Everyday'],['Alarm clock','alarm,clock,wake','Everyday'],['Remote control','remote,control,television','Everyday'],['Washing machine','washing,machine,clothes','Everyday'],['Vacuum cleaner','vacuum,cleaner,dust','Everyday'],['Sunglasses','sunglasses,sun,glasses','Everyday'],['Elevator','elevator,lift,floor','Everyday'],
['Astronaut','astronaut,space,moon','People'],['Magician','magician,magic,trick','People'],['Detective','detective,crime,clue','People'],['Lifeguard','lifeguard,swim,pool','People'],['Chef','chef,cook,kitchen','People'],['Dentist','dentist,teeth,tooth','People'],['Pirate','pirate,ship,treasure','People'],['Snowman','snowman,snow,carrot','Wild Cards'],
['Treasure map','treasure,map,gold','Wild Cards'],['Haunted house','haunted,house,ghost','Wild Cards'],['Traffic jam','traffic,jam,car','Wild Cards'],['Shooting star','shooting,star,sky','Wild Cards'],['Bubble bath','bubble,bath,soap','Wild Cards'],['Sandcastle','sandcastle,sand,castle','Wild Cards'],['Hot air balloon','hot,air,balloon','Wild Cards'],['Lighthouse','lighthouse,light,ship','Wild Cards'],['Snow globe','snow,globe,shake','Wild Cards'],['Fortune cookie','fortune,cookie,message','Wild Cards']
].map(([answer,words,category],id)=>({id,answer,forbidden:words.split(','),category}));
export const normalize=s=>String(s).toLowerCase().normalize('NFKD').replace(/[^a-z0-9]/g,'');
export const blocked=(text,p)=>[p.answer,...p.forbidden].some(w=>normalize(text).includes(normalize(w)));
export function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=crypto.getRandomValues(new Uint32Array(1))[0]%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
export function start(s,now){s.phase='question';s.startsAt=now+3000;s.deadline=s.startsAt+(s.index>=s.order.length?40000:60000);s.clues=[];s.solved={};s.attempts={};s.lastGuess={};for(const p of Object.values(s.players))p.roundPoints=0;}
export function advance(s,now){if(s.phase==='question'&&now>=s.deadline){s.phase='reveal';s.deadline=now+10000;return true}if(s.phase==='reveal'&&now>=s.deadline){s.index++;if(s.index>=s.order.length*2)s.phase='ended';else start(s,now);return true}return false}
export function view(s,seat,now,display=false){const giver=s.order?.[s.index%s.order.length],prompt=BANK[s.deck?.[s.index]];return {code:s.code,game:s.game,phase:s.phase,index:s.index,serverNow:now,startsAt:s.startsAt,deadline:s.deadline,host:!display&&seat===s.owner,display,displayKey:seat===s.owner&&!display?s.displayKey:undefined,rounds:(s.order?.length||0)*2,lightning:s.index>=s.order?.length,giver:s.players[giver]?.name,isGiver:!display&&seat===giver,category:prompt?.category,prompt:!display&&seat===giver&&s.phase==='question'?prompt:undefined,answer:s.phase==='reveal'||s.phase==='ended'?prompt?.answer:undefined,clues:s.clues||[],solved:!display&&!!s.solved?.[seat],lastGuess:!display?s.lastGuess?.[seat]:undefined,players:Object.entries(s.players).map(([id,p])=>({name:p.name,score:p.score,ready:p.ready,roundPoints:p.roundPoints||0,you:!display&&id===seat,solved:!!s.solved?.[id]})).sort((a,b)=>b.score-a.score)};}
